#!/bin/sh
while true
do
    NOTIFICATION=`inotifywait -q ~/irc @. -r -e OPEN`
    FILE=`echo "$NOTIFICATION" | cut -f3 -d ' '`
    DIRECTORY=`echo "$NOTIFICATION" | cut -f1 -d ' '`
    test "$FILE" = "out" && (
        SERVER=`echo "$DIRECTORY" | cut -f5 -d '/'`
        ENTITY=`echo "$DIRECTORY" | cut -f6 -d '/'`

        pgrep -f "./uii $SERVER $ENTITY" || \
            nohup x-terminal-emulator -e "./uii $SERVER $ENTITY" > /dev/null 2>&1 &
    )
done
