#!/bin/sh
while true ; do
inotifywait -qq -e OPEN "$HOME/irc/$1/$2/out" && \
    tail -n 1 $HOME/irc/$1/$2/out | cut -b20- | grep $3 -q && \
    notify-send \
        "`tail -n 1 $HOME/irc/$1/$2/out | cut -b18-`" \
        "in $2 @ $1" \
        -i gtk-dialog-info ;
done ;

