#!/bin/sh
FORBIDDEN=`printf "\001-\011\013-\037"`
tail -n 20 -f "$1" | \
    stdbuf -oL tr -d "$FORBIDDEN" | \
    stdbuf -oL cut -f3- -d' ' | \
    stdbuf -oL grep "..$2" | \
    stdbuf -i0 -oL cut -f3- -d' '
