#!/bin/sh
FORBIDDEN=`printf "\001-\011\013-\037"`
SERVER=`dirname \`dirname "$1"\``/out
LINES=`expr \`tput lines\` / 2`
tail -q -n "$LINES" -f "$SERVER" "$1" | \
    stdbuf -oL tr -d "$FORBIDDEN" | \
    stdbuf -oL sed "s/ $2/ "`tput bold`"$2"`tput sgr0`"\a/g" | \
    stdbuf -oL cut -c12-
