#!/bin/sh
FORBIDDEN=`printf "\001-\011\013-\037"`
tail -n 80 -f "$1" | \
    stdbuf -oL tr -d "$FORBIDDEN" | \
    stdbuf -oL sed "s/ $2/ "`tput bold`"$2"`tput sgr0`"\a/g" | \
    stdbuf -oL cut -c12-
