#!/bin/sh
set -e

INFILE="$HOME/irc/$1/in"
(test -e "$INFILE" && lsof -Fc "$INFILE" | grep -q "cii") || \
    (
        nohup ii -s "$1" > /dev/null 2>&1 &
        inotifywait "$INFILE"
    )

pgrep iiinotify > /dev/null 2>&1 || \
    nohup ./iiinotify > /dev/null 2>&1 &

test -n "$3" && echo "/n $3" > "$HOME/irc/$1/in"
test -n "$4" && \
    (
        test -e "$HOME/irc/$1/nickserv/in" || \
            inotifywait "$HOME/irc/$1/nickserv/out"
        echo "identify $4" > "$HOME/irc/$1/nickserv/in"
    )

echo "/j $2" > "$HOME/irc/$1/in"

ENTITY_ESCAPED=`echo "$2" | tr '/' '_'`
splitvt -bottom -s 80 -f \
    -upper "./iioutput $HOME/irc/$1/$ENTITY_ESCAPED/out" \
    -lower "./iiinput $HOME/irc/$1/$ENTITY_ESCAPED/in $2"
