#!/bin/sh
./iiconnected "$1" && ( \
    echo "/j $2" > $HOME/irc/$1/in  && \
    splitvt \
        -upper "tail -n 40 -f $HOME/irc/$1/$2/out" \
        -lower "./iiinput $1 $2" \
        -bottom \
        -s 40 -f \
) || \
echo "ii is not connected to $1, exiting …" && \
    false
