#!/bin/sh
set -e

INFILE="$HOME/irc/$1/in"
(test -e "$INFILE" && lsof -Fc "$INFILE" | grep -q "cii") || \
    (
        nohup ii -s "$1" > /dev/null 2>&1 &
        inotifywait "$INFILE"
    )

pgrep iiinotify > /dev/null 2>&1 || \
    nohup ./iiinotify > /dev/null 2>&1 &

test -n "$3" && echo "/n $3" > "$INFILE"
test -n "$4" && echo "/j nickserv identify $4" > "$INFILE"

echo "/j $2" > "$INFILE"

splitvt -bottom -s 80 -f -t "$2 @ $1 – uii" \
    -upper "./iioutput $HOME/irc/$1/$2/out ${3-$USER}" \
    -lower "./iiinput $HOME/irc/$1/$2/in $2"
